### ISSUE TITLE
Spectogram out of sync

### ISSUE THREAD

**Issue by paulobarros** [mike-brady/Spectrogram-Player#1]
Hey Mike, first of all thank you for developing this player. I am having a problem when using mp3 audio with a jpg spectogram image. They are out of sync, the audio is a little bit faster than the image rolling. Do you have any idea what my problem could be? I am attaching the audio file and image I've tested with.

The settings I've used:

```
<div class="spectrogram-player" data-width="600" data-height="180" data-freq-min="0" data-freq-max="12">
    <img src="tururim.jpg" />
    <audio controls controlsList="nodownload">
      <source src="tururim.mp3" type="audio/mp3">
    </audio>
  </div>
```

Audio: [Tururim](https://s3.amazonaws.com/media.wikiaves.com.br/recordings/808/808970_6c131c7d70d63cb28a298308a365b52c.mp3)

Spectogram: [Tururim Image](https://s3.amazonaws.com/media.wikiaves.com.br/recordings/808/808970_6c131c7d70d63cb28a298308a365b52c.jpg)

**Comment by mike-brady** [comment]
Hi, sorry for the late response! It appears your image is cut short and doesn't contain the entire audio file in the spectrogram. Here is one I generated from your audio file using this [online tool](https://convert.ing-now.com/audio-spectrogram-creator/). The area in the green rectangle is what's missing from the one you are using.

![test_spectrogram](https://github.com/mike-brady/Spectrogram-Player/assets/33209281/10c15225-f875-4abc-aeac-d7bf471f6835)

**Comment by paulobarros** [comment]
Thank you! I am scrapping the audio data from a website, I also scrapped the image, I will check if there is a full version of the spectrogram. Thank you very much for the help!
